/****************************************************************-*- C++ -*-****
 * Copyright (c) 2025 NVIDIA Corporation & Affiliates.                         *
 * All rights reserved.                                                        *
 *                                                                             *
 * This source code and the accompanying materials are made available under    *
 * the terms of the Apache License 2.0 which accompanies this distribution.    *
 ******************************************************************************/

#pragma once

#include "../operator_pool.h"

namespace cudaq::solvers {

/// @brief CEO (Coupled Exchange Operator) operator pool is a class which
/// generates a pool of CEO operators for use in quantum algorithms, like
/// Adapt-VQE.
/// @details This class extends the operator_pool interface therefore inherits
/// the extension_point template, allowing for runtime extensibility. CEO
/// combines qubit excitation operators, which preserve particle number and
/// Sz quantum numbers, but do not include Z parity strings. Combining the
/// qubit excitation together allows for a simpler circuit implementation.
/// For more details, see the CEO paper (https://arxiv.org/abs/2407.08696).
class ceo : public operator_pool {

public:
  /// @brief Generate a vector of spin operators based on the provided
  /// configuration.
  /// @details The CEO operator pool is generated by omitting the imaginary unit
  /// 'i' coefficient that is present in the CEO paper
  /// (https://arxiv.org/abs/2407.08696), which simplifies the use for running
  /// ADAPT-VQE. The operator pool includes alpha singles, beta singles, alpha
  /// doubles, beta doubles, and mixed doubles.
  /// @param config A heterogeneous map containing configuration parameters for
  /// operator generation.
  /// @return A vector of cudaq::spin_op objects representing the generated
  /// operator pool.
  std::vector<cudaq::spin_op>
  generate(const heterogeneous_map &config) const override;

  /// @brief Call to macro for defining the creator function for an extension
  /// @details This function is used by the extension point mechanism to create
  /// instances of the ceo class.
  CUDAQ_EXTENSION_CREATOR_FUNCTION(operator_pool, ceo)
};
/// @brief Register the ceo extension type with the CUDA-Q framework
CUDAQ_REGISTER_TYPE(ceo)

} // namespace cudaq::solvers
